### ISSUE TITLE
Need to add tester emails to AWS SES

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#151]
Currently AWS-WPS in dev account only sends emails to registered recipients.  If sandbox is to be run in the dev account then email addresses for all testers will have to be added or the whitelist removed

**Comment by lwgordonimos** [comment]
This was a conscious decision to initially leave the dev SES in sandbox mode. The advantage is that dev emails can't ever leak to the wider world, potentially affecting our overall domain reputation and/or sending emails from dev systems to real people.

Currently, any mail sent to aodn.org.au addresses is permitted, or explicitly verified addresses.

The options are:
1) verify all tester addresses
2) use an aodn.org.au address for testing
3) submit a ticket to AWS to lift the "sandbox mode" restriction for dev SES

I'd probably be in favour of leaving it sandboxed, since adding addresses for testers is very simple.

**Comment by jonescc** [comment]
Not an issue in sandbox - all email addresses allowed.
