### ISSUE TITLE
Stack update failure breaks stack

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#166]
### To reproduce 

Try deploying sandbox but leave environment as dev (or other breaking change)

### What happens

Stack update fails (unknown vpc in the example above) and ends up in a ROLLBACK_COMPLETE status and stack is in an inconsistent state (broken - van't be used)

### What I expect to happen

I get errors and rollback to a consistent state or we can't get into this situation (e.g. have a sandbox deploy job with correct params).

**Comment by jonescc** [comment]
Clouf formation event log for above [failed.log](https://github.com/aodn/aws-wps/files/1519915/failed.log)

**Comment by akashisama** [comment]
Strangely it seems have  deleted the previous instance of the stack and then tried to bring up a new stack with the same name, rather than performing an update. This meant there was nothing to roll back to. I can't remember ever seeing this during dev work and the stack @jonescc  is running in dev right now looks to be updating.

**Comment by jonescc** [comment]
Don't believe this is possible anymore as this is controlled in the template
