### ISSUE TITLE
Limit reached error adding sumologic endpoint

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#167]
### To reproduce

Try to deploy sandbox with sumologic endpoint specified

### What happens

Update fails with 
```
        }, 
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:104044260116:stack/aws-wps-sandbox/12594420-d62a-11e7-a9bd-5081eaa90811", 
            "EventId": "BatchJobLogsSubscriptionFilter-CREATE_FAILED-2017-11-30T23:57:50.167Z", 
            "ResourceStatus": "CREATE_FAILED", 
            "ResourceType": "AWS::Logs::SubscriptionFilter", 
            "Timestamp": "2017-11-30T23:57:50.167Z", 
            "ResourceStatusReason": "Resource limit exceeded.", 
            "StackName": "aws-wps-sandbox", 
            "ResourceProperties": "{\"FilterPattern\":\"\",\"LogGroupName\":\"/aws/batch/job\",\"DestinationArn\":\"arn:aws:lambda:ap-southeast-2:104044260116:function:SumoLogic-WPS-aws-wps-sandbox\"}\n", 
            "PhysicalResourceId": "", 
            "LogicalResourceId": "BatchJobLogsSubscriptionFilter"
        }, 
```

Full log [failed-2.log](https://github.com/aodn/aws-wps/files/1519931/failed-2.log)

### What I expect to happen

The update is successful

**Comment by ccmoloney** [comment]
I think that this occurred because there was a subscription filter (trigger for the Sumo lambda) manually created against the log group (/aws/batch/job) already - so that we could start looking at the Sumo log search changes that would be required.  It seems that you can only ever have one lambda triggered by cloudwatch events on a log group (maybe).

I don't think this will cause us an issue in subsequent environments - since there won't be a manually-created version of the sumo lambda & trigger already in a new environment.

**Comment by ccmoloney** [comment]
Yep - it's a hard limit on the number of cloudwatch log subscriptions you can have on a given log group - the limit being 1!  This is a hard limit at this stage - so I will close this - since there is no resolution possible right now.

The only resolution is to ensure that there are no subscriptions registered against the /aws/batch/jobs (this is the one which is common to all stacks running in the AWS account) log group prior to running the stack creation.
